extern const GeoLayout mia_Mouth1[];
extern const GeoLayout mia_Mouth2[];
extern const GeoLayout mia_Mouth3[];
extern const GeoLayout mia_Mouth4[];
extern const GeoLayout mia_Mouth5[];
extern const GeoLayout mia_Mouth6[];
extern const GeoLayout mia_Mouth7[];
extern const GeoLayout mia_Head_Left[];
extern const GeoLayout mia_Head_Right[];
extern const GeoLayout mia_Head_Up[];
extern const GeoLayout mia_Head_Down[];
extern const GeoLayout mia_Head_Dead[];
extern const GeoLayout mia_Head_Extra1[];
extern const GeoLayout mia_Head_Extra2[];
extern const GeoLayout mia_Capless_Head_Switch_Option_Capless_Head_Left[];
extern const GeoLayout mia_Capless_Head_Switch_Option_Capless_Head_Right[];
extern const GeoLayout mia_Capless_Head_Switch_Option_Capless_Head_Up[];
extern const GeoLayout mia_Capless_Head_Switch_Option_Capless_Head_Down[];
extern const GeoLayout mia_Capless_Head_Switch_Option_Capless_Head_Dead[];
extern const GeoLayout mia_Capless_Head_Switch_Option_Head_Extra1_Capless[];
extern const GeoLayout mia_Capless_Head_Switch_Option_Head_Extra2_Capless[];
extern const GeoLayout mia_Capless_Head[];
extern const GeoLayout mia_MaskArmature[];
extern const GeoLayout mia_Left_Hand_Open[];
extern const GeoLayout mia_Left_Hand_Peace[];
extern const GeoLayout mia_Right_Hand_Open[];
extern const GeoLayout mia_Right_Hand_Peace[];
extern const GeoLayout mia_Right_Hand_Cap[];
extern const GeoLayout mia_Right_Hand_Wing_Cap[];
extern const GeoLayout mia_Mouth1_opt_1[];
extern const GeoLayout mia_Mouth2_opt_1[];
extern const GeoLayout mia_Mouth3_opt_1[];
extern const GeoLayout mia_Mouth4_opt_1[];
extern const GeoLayout mia_Mouth5_opt_1[];
extern const GeoLayout mia_Mouth6_opt_1[];
extern const GeoLayout mia_Mouth7_opt_1[];
extern const GeoLayout mia_geo_opt_1[];
extern const GeoLayout mia_Mouth1_opt_2[];
extern const GeoLayout mia_Mouth2_opt_2[];
extern const GeoLayout mia_Mouth3_opt_2[];
extern const GeoLayout mia_Mouth4_opt_2[];
extern const GeoLayout mia_Mouth5_opt_2[];
extern const GeoLayout mia_Mouth6_opt_2[];
extern const GeoLayout mia_Mouth7_opt_2[];
extern const GeoLayout mia_geo_opt_2[];
extern const GeoLayout mia_Mouth1_opt_1_1[];
extern const GeoLayout mia_Mouth2_opt_1_1[];
extern const GeoLayout mia_Mouth3_opt_1_1[];
extern const GeoLayout mia_Mouth4_opt_1_1[];
extern const GeoLayout mia_Mouth5_opt_1_1[];
extern const GeoLayout mia_Mouth6_opt_1_1[];
extern const GeoLayout mia_Mouth7_opt_1_1[];
extern const GeoLayout mia_geo_opt_1_1[];
extern const GeoLayout mia_Mouth1_opt_2_1[];
extern const GeoLayout mia_Mouth2_opt_2_1[];
extern const GeoLayout mia_Mouth3_opt_2_1[];
extern const GeoLayout mia_Mouth4_opt_2_1[];
extern const GeoLayout mia_Mouth5_opt_2_1[];
extern const GeoLayout mia_Mouth6_opt_2_1[];
extern const GeoLayout mia_Mouth7_opt_2_1[];
extern const GeoLayout mia_geo_opt_2_1[];
extern const GeoLayout mia_Mouth1_opt_1_2[];
extern const GeoLayout mia_Mouth2_opt_1_2[];
extern const GeoLayout mia_Mouth3_opt_1_2[];
extern const GeoLayout mia_Mouth4_opt_1_2[];
extern const GeoLayout mia_Mouth5_opt_1_2[];
extern const GeoLayout mia_Mouth6_opt_1_2[];
extern const GeoLayout mia_Mouth7_opt_1_2[];
extern const GeoLayout mia_Mouth1_opt_1_opt_1[];
extern const GeoLayout mia_Mouth2_opt_1_opt_1[];
extern const GeoLayout mia_Mouth3_opt_1_opt_1[];
extern const GeoLayout mia_Mouth4_opt_1_opt_1[];
extern const GeoLayout mia_Mouth5_opt_1_opt_1[];
extern const GeoLayout mia_Mouth6_opt_1_opt_1[];
extern const GeoLayout mia_Mouth7_opt_1_opt_1[];
extern const GeoLayout mia_geo_opt_1_2_opt_1_opt_1[];
extern const GeoLayout mia_Mouth1_opt_1_opt_2[];
extern const GeoLayout mia_Mouth2_opt_1_opt_2[];
extern const GeoLayout mia_Mouth3_opt_1_opt_2[];
extern const GeoLayout mia_Mouth4_opt_1_opt_2[];
extern const GeoLayout mia_Mouth5_opt_1_opt_2[];
extern const GeoLayout mia_Mouth6_opt_1_opt_2[];
extern const GeoLayout mia_Mouth7_opt_1_opt_2[];
extern const GeoLayout mia_geo_opt_1_2_opt_1_opt_2[];
extern const GeoLayout mia_Head_Left_opt_1[];
extern const GeoLayout mia_Mouth1_opt_1_3[];
extern const GeoLayout mia_Mouth2_opt_1_3[];
extern const GeoLayout mia_Mouth3_opt_1_3[];
extern const GeoLayout mia_Mouth4_opt_1_3[];
extern const GeoLayout mia_Mouth5_opt_1_3[];
extern const GeoLayout mia_Mouth6_opt_1_3[];
extern const GeoLayout mia_Mouth7_opt_1_3[];
extern const GeoLayout mia_Head_Right_opt_1[];
extern const GeoLayout mia_Mouth1_opt_1_4[];
extern const GeoLayout mia_Mouth2_opt_1_4[];
extern const GeoLayout mia_Mouth3_opt_1_4[];
extern const GeoLayout mia_Mouth4_opt_1_4[];
extern const GeoLayout mia_Mouth5_opt_1_4[];
extern const GeoLayout mia_Mouth6_opt_1_4[];
extern const GeoLayout mia_Mouth7_opt_1_4[];
extern const GeoLayout mia_Head_Up_opt_1[];
extern const GeoLayout mia_Mouth1_opt_1_5[];
extern const GeoLayout mia_Mouth2_opt_1_5[];
extern const GeoLayout mia_Mouth3_opt_1_5[];
extern const GeoLayout mia_Mouth4_opt_1_5[];
extern const GeoLayout mia_Mouth5_opt_1_5[];
extern const GeoLayout mia_Mouth6_opt_1_5[];
extern const GeoLayout mia_Mouth7_opt_1_5[];
extern const GeoLayout mia_Head_Down_opt_1[];
extern const GeoLayout mia_Mouth1_opt_1_6[];
extern const GeoLayout mia_Mouth2_opt_1_6[];
extern const GeoLayout mia_Mouth3_opt_1_6[];
extern const GeoLayout mia_Mouth4_opt_1_6[];
extern const GeoLayout mia_Mouth5_opt_1_6[];
extern const GeoLayout mia_Mouth6_opt_1_6[];
extern const GeoLayout mia_Mouth7_opt_1_6[];
extern const GeoLayout mia_Head_Dead_opt_1[];
extern const GeoLayout mia_Head_Extra1_opt_1[];
extern const GeoLayout mia_Mouth1_opt_1_7[];
extern const GeoLayout mia_Mouth2_opt_1_7[];
extern const GeoLayout mia_Mouth3_opt_1_7[];
extern const GeoLayout mia_Mouth4_opt_1_7[];
extern const GeoLayout mia_Mouth5_opt_1_7[];
extern const GeoLayout mia_Mouth6_opt_1_7[];
extern const GeoLayout mia_Mouth7_opt_1_7[];
extern const GeoLayout mia_Head_Extra2_opt_1[];
extern const GeoLayout mia_Mouth1_opt_1_8[];
extern const GeoLayout mia_Mouth2_opt_1_8[];
extern const GeoLayout mia_Mouth3_opt_1_8[];
extern const GeoLayout mia_Mouth4_opt_1_8[];
extern const GeoLayout mia_Mouth5_opt_1_8[];
extern const GeoLayout mia_Mouth6_opt_1_8[];
extern const GeoLayout mia_Mouth7_opt_1_8[];
extern const GeoLayout mia_Capless_Head_opt_1[];
extern const GeoLayout mia_Mouth1_opt_1_9[];
extern const GeoLayout mia_Mouth2_opt_1_9[];
extern const GeoLayout mia_Mouth3_opt_1_9[];
extern const GeoLayout mia_Mouth4_opt_1_9[];
extern const GeoLayout mia_Mouth5_opt_1_9[];
extern const GeoLayout mia_Mouth6_opt_1_9[];
extern const GeoLayout mia_Mouth7_opt_1_9[];
extern const GeoLayout mia_geo_opt_1_1_opt_1[];
extern const GeoLayout mia_Mouth1_opt_1_1_opt_1[];
extern const GeoLayout mia_Mouth2_opt_1_1_opt_1[];
extern const GeoLayout mia_Mouth3_opt_1_1_opt_1[];
extern const GeoLayout mia_Mouth4_opt_1_1_opt_1[];
extern const GeoLayout mia_Mouth5_opt_1_1_opt_1[];
extern const GeoLayout mia_Mouth6_opt_1_1_opt_1[];
extern const GeoLayout mia_Mouth7_opt_1_1_opt_1[];
extern const GeoLayout mia_geo_opt_2_1_opt_1[];
extern const GeoLayout mia_Mouth1_opt_2_1_opt_1[];
extern const GeoLayout mia_Mouth2_opt_2_1_opt_1[];
extern const GeoLayout mia_Mouth3_opt_2_1_opt_1[];
extern const GeoLayout mia_Mouth4_opt_2_1_opt_1[];
extern const GeoLayout mia_Mouth5_opt_2_1_opt_1[];
extern const GeoLayout mia_Mouth6_opt_2_1_opt_1[];
extern const GeoLayout mia_Mouth7_opt_2_1_opt_1[];
extern const GeoLayout mia_Capless_Head_Switch_Option_Capless_Head_Left_opt_1[];
extern const GeoLayout mia_Mouth1_opt_1_10[];
extern const GeoLayout mia_Mouth2_opt_1_10[];
extern const GeoLayout mia_Mouth3_opt_1_10[];
extern const GeoLayout mia_Mouth4_opt_1_10[];
extern const GeoLayout mia_Mouth5_opt_1_10[];
extern const GeoLayout mia_Mouth6_opt_1_10[];
extern const GeoLayout mia_Mouth7_opt_1_10[];
extern const GeoLayout mia_Capless_Head_Switch_Option_Capless_Head_Right_opt_1[];
extern const GeoLayout mia_Mouth1_opt_1_11[];
extern const GeoLayout mia_Mouth2_opt_1_11[];
extern const GeoLayout mia_Mouth3_opt_1_11[];
extern const GeoLayout mia_Mouth4_opt_1_11[];
extern const GeoLayout mia_Mouth5_opt_1_11[];
extern const GeoLayout mia_Mouth6_opt_1_11[];
extern const GeoLayout mia_Mouth7_opt_1_11[];
extern const GeoLayout mia_Capless_Head_Switch_Option_Capless_Head_Up_opt_1[];
extern const GeoLayout mia_Mouth1_opt_1_12[];
extern const GeoLayout mia_Mouth2_opt_1_12[];
extern const GeoLayout mia_Mouth3_opt_1_12[];
extern const GeoLayout mia_Mouth4_opt_1_12[];
extern const GeoLayout mia_Mouth5_opt_1_12[];
extern const GeoLayout mia_Mouth6_opt_1_12[];
extern const GeoLayout mia_Mouth7_opt_1_12[];
extern const GeoLayout mia_Capless_Head_Switch_Option_Capless_Head_Down_opt_1[];
extern const GeoLayout mia_Mouth1_opt_1_13[];
extern const GeoLayout mia_Mouth2_opt_1_13[];
extern const GeoLayout mia_Mouth3_opt_1_13[];
extern const GeoLayout mia_Mouth4_opt_1_13[];
extern const GeoLayout mia_Mouth5_opt_1_13[];
extern const GeoLayout mia_Mouth6_opt_1_13[];
extern const GeoLayout mia_Mouth7_opt_1_13[];
extern const GeoLayout mia_Capless_Head_Switch_Option_Capless_Head_Dead_opt_1[];
extern const GeoLayout mia_Capless_Head_Switch_Option_Head_Extra1_Capless_opt_1[];
extern const GeoLayout mia_Mouth1_opt_1_14[];
extern const GeoLayout mia_Mouth2_opt_1_14[];
extern const GeoLayout mia_Mouth3_opt_1_14[];
extern const GeoLayout mia_Mouth4_opt_1_14[];
extern const GeoLayout mia_Mouth5_opt_1_14[];
extern const GeoLayout mia_Mouth6_opt_1_14[];
extern const GeoLayout mia_Mouth7_opt_1_14[];
extern const GeoLayout mia_Capless_Head_Switch_Option_Head_Extra2_Capless_opt_1[];
extern const GeoLayout mia_Mouth1_opt_1_15[];
extern const GeoLayout mia_Mouth2_opt_1_15[];
extern const GeoLayout mia_Mouth3_opt_1_15[];
extern const GeoLayout mia_Mouth4_opt_1_15[];
extern const GeoLayout mia_Mouth5_opt_1_15[];
extern const GeoLayout mia_Mouth6_opt_1_15[];
extern const GeoLayout mia_Mouth7_opt_1_15[];
extern const GeoLayout mia_MaskArmature_opt_1[];
extern const GeoLayout mia_Left_Hand_Open_opt_1[];
extern const GeoLayout mia_Left_Hand_Peace_opt_1[];
extern const GeoLayout mia_Left_Hand_Open_opt_1_1[];
extern const GeoLayout mia_Right_Hand_Open_opt_1[];
extern const GeoLayout mia_Right_Hand_Peace_opt_1[];
extern const GeoLayout mia_Right_Hand_Cap_opt_1[];
extern const GeoLayout mia_Right_Hand_Wing_Cap_opt_1[];
extern const GeoLayout mia_geo_opt_1_2[];
extern const GeoLayout mia_Mouth1_opt_2_2[];
extern const GeoLayout mia_Mouth2_opt_2_2[];
extern const GeoLayout mia_Mouth3_opt_2_2[];
extern const GeoLayout mia_Mouth4_opt_2_2[];
extern const GeoLayout mia_Mouth5_opt_2_2[];
extern const GeoLayout mia_Mouth6_opt_2_2[];
extern const GeoLayout mia_Mouth7_opt_2_2[];
extern const GeoLayout mia_Mouth1_opt_2_opt_1[];
extern const GeoLayout mia_Mouth2_opt_2_opt_1[];
extern const GeoLayout mia_Mouth3_opt_2_opt_1[];
extern const GeoLayout mia_Mouth4_opt_2_opt_1[];
extern const GeoLayout mia_Mouth5_opt_2_opt_1[];
extern const GeoLayout mia_Mouth6_opt_2_opt_1[];
extern const GeoLayout mia_Mouth7_opt_2_opt_1[];
extern const GeoLayout mia_geo_opt_2_2_opt_2_opt_1[];
extern const GeoLayout mia_Mouth1_opt_2_opt_2[];
extern const GeoLayout mia_Mouth2_opt_2_opt_2[];
extern const GeoLayout mia_Mouth3_opt_2_opt_2[];
extern const GeoLayout mia_Mouth4_opt_2_opt_2[];
extern const GeoLayout mia_Mouth5_opt_2_opt_2[];
extern const GeoLayout mia_Mouth6_opt_2_opt_2[];
extern const GeoLayout mia_Mouth7_opt_2_opt_2[];
extern const GeoLayout mia_geo_opt_2_2_opt_2_opt_2[];
extern const GeoLayout mia_Head_Left_opt_2[];
extern const GeoLayout mia_Mouth1_opt_2_3[];
extern const GeoLayout mia_Mouth2_opt_2_3[];
extern const GeoLayout mia_Mouth3_opt_2_3[];
extern const GeoLayout mia_Mouth4_opt_2_3[];
extern const GeoLayout mia_Mouth5_opt_2_3[];
extern const GeoLayout mia_Mouth6_opt_2_3[];
extern const GeoLayout mia_Mouth7_opt_2_3[];
extern const GeoLayout mia_Head_Right_opt_2[];
extern const GeoLayout mia_Mouth1_opt_2_4[];
extern const GeoLayout mia_Mouth2_opt_2_4[];
extern const GeoLayout mia_Mouth3_opt_2_4[];
extern const GeoLayout mia_Mouth4_opt_2_4[];
extern const GeoLayout mia_Mouth5_opt_2_4[];
extern const GeoLayout mia_Mouth6_opt_2_4[];
extern const GeoLayout mia_Mouth7_opt_2_4[];
extern const GeoLayout mia_Head_Up_opt_2[];
extern const GeoLayout mia_Mouth1_opt_2_5[];
extern const GeoLayout mia_Mouth2_opt_2_5[];
extern const GeoLayout mia_Mouth3_opt_2_5[];
extern const GeoLayout mia_Mouth4_opt_2_5[];
extern const GeoLayout mia_Mouth5_opt_2_5[];
extern const GeoLayout mia_Mouth6_opt_2_5[];
extern const GeoLayout mia_Mouth7_opt_2_5[];
extern const GeoLayout mia_Head_Down_opt_2[];
extern const GeoLayout mia_Mouth1_opt_2_6[];
extern const GeoLayout mia_Mouth2_opt_2_6[];
extern const GeoLayout mia_Mouth3_opt_2_6[];
extern const GeoLayout mia_Mouth4_opt_2_6[];
extern const GeoLayout mia_Mouth5_opt_2_6[];
extern const GeoLayout mia_Mouth6_opt_2_6[];
extern const GeoLayout mia_Mouth7_opt_2_6[];
extern const GeoLayout mia_Head_Dead_opt_2[];
extern const GeoLayout mia_Head_Extra1_opt_2[];
extern const GeoLayout mia_Mouth1_opt_2_7[];
extern const GeoLayout mia_Mouth2_opt_2_7[];
extern const GeoLayout mia_Mouth3_opt_2_7[];
extern const GeoLayout mia_Mouth4_opt_2_7[];
extern const GeoLayout mia_Mouth5_opt_2_7[];
extern const GeoLayout mia_Mouth6_opt_2_7[];
extern const GeoLayout mia_Mouth7_opt_2_7[];
extern const GeoLayout mia_Head_Extra2_opt_2[];
extern const GeoLayout mia_Mouth1_opt_2_8[];
extern const GeoLayout mia_Mouth2_opt_2_8[];
extern const GeoLayout mia_Mouth3_opt_2_8[];
extern const GeoLayout mia_Mouth4_opt_2_8[];
extern const GeoLayout mia_Mouth5_opt_2_8[];
extern const GeoLayout mia_Mouth6_opt_2_8[];
extern const GeoLayout mia_Mouth7_opt_2_8[];
extern const GeoLayout mia_Capless_Head_opt_2[];
extern const GeoLayout mia_Mouth1_opt_2_9[];
extern const GeoLayout mia_Mouth2_opt_2_9[];
extern const GeoLayout mia_Mouth3_opt_2_9[];
extern const GeoLayout mia_Mouth4_opt_2_9[];
extern const GeoLayout mia_Mouth5_opt_2_9[];
extern const GeoLayout mia_Mouth6_opt_2_9[];
extern const GeoLayout mia_Mouth7_opt_2_9[];
extern const GeoLayout mia_geo_opt_1_1_opt_2[];
extern const GeoLayout mia_Mouth1_opt_1_1_opt_2[];
extern const GeoLayout mia_Mouth2_opt_1_1_opt_2[];
extern const GeoLayout mia_Mouth3_opt_1_1_opt_2[];
extern const GeoLayout mia_Mouth4_opt_1_1_opt_2[];
extern const GeoLayout mia_Mouth5_opt_1_1_opt_2[];
extern const GeoLayout mia_Mouth6_opt_1_1_opt_2[];
extern const GeoLayout mia_Mouth7_opt_1_1_opt_2[];
extern const GeoLayout mia_geo_opt_2_1_opt_2[];
extern const GeoLayout mia_Mouth1_opt_2_1_opt_2[];
extern const GeoLayout mia_Mouth2_opt_2_1_opt_2[];
extern const GeoLayout mia_Mouth3_opt_2_1_opt_2[];
extern const GeoLayout mia_Mouth4_opt_2_1_opt_2[];
extern const GeoLayout mia_Mouth5_opt_2_1_opt_2[];
extern const GeoLayout mia_Mouth6_opt_2_1_opt_2[];
extern const GeoLayout mia_Mouth7_opt_2_1_opt_2[];
extern const GeoLayout mia_Capless_Head_Switch_Option_Capless_Head_Left_opt_2[];
extern const GeoLayout mia_Mouth1_opt_2_10[];
extern const GeoLayout mia_Mouth2_opt_2_10[];
extern const GeoLayout mia_Mouth3_opt_2_10[];
extern const GeoLayout mia_Mouth4_opt_2_10[];
extern const GeoLayout mia_Mouth5_opt_2_10[];
extern const GeoLayout mia_Mouth6_opt_2_10[];
extern const GeoLayout mia_Mouth7_opt_2_10[];
extern const GeoLayout mia_Capless_Head_Switch_Option_Capless_Head_Right_opt_2[];
extern const GeoLayout mia_Mouth1_opt_2_11[];
extern const GeoLayout mia_Mouth2_opt_2_11[];
extern const GeoLayout mia_Mouth3_opt_2_11[];
extern const GeoLayout mia_Mouth4_opt_2_11[];
extern const GeoLayout mia_Mouth5_opt_2_11[];
extern const GeoLayout mia_Mouth6_opt_2_11[];
extern const GeoLayout mia_Mouth7_opt_2_11[];
extern const GeoLayout mia_Capless_Head_Switch_Option_Capless_Head_Up_opt_2[];
extern const GeoLayout mia_Mouth1_opt_2_12[];
extern const GeoLayout mia_Mouth2_opt_2_12[];
extern const GeoLayout mia_Mouth3_opt_2_12[];
extern const GeoLayout mia_Mouth4_opt_2_12[];
extern const GeoLayout mia_Mouth5_opt_2_12[];
extern const GeoLayout mia_Mouth6_opt_2_12[];
extern const GeoLayout mia_Mouth7_opt_2_12[];
extern const GeoLayout mia_Capless_Head_Switch_Option_Capless_Head_Down_opt_2[];
extern const GeoLayout mia_Mouth1_opt_2_13[];
extern const GeoLayout mia_Mouth2_opt_2_13[];
extern const GeoLayout mia_Mouth3_opt_2_13[];
extern const GeoLayout mia_Mouth4_opt_2_13[];
extern const GeoLayout mia_Mouth5_opt_2_13[];
extern const GeoLayout mia_Mouth6_opt_2_13[];
extern const GeoLayout mia_Mouth7_opt_2_13[];
extern const GeoLayout mia_Capless_Head_Switch_Option_Capless_Head_Dead_opt_2[];
extern const GeoLayout mia_Capless_Head_Switch_Option_Head_Extra1_Capless_opt_2[];
extern const GeoLayout mia_Mouth1_opt_2_14[];
extern const GeoLayout mia_Mouth2_opt_2_14[];
extern const GeoLayout mia_Mouth3_opt_2_14[];
extern const GeoLayout mia_Mouth4_opt_2_14[];
extern const GeoLayout mia_Mouth5_opt_2_14[];
extern const GeoLayout mia_Mouth6_opt_2_14[];
extern const GeoLayout mia_Mouth7_opt_2_14[];
extern const GeoLayout mia_Capless_Head_Switch_Option_Head_Extra2_Capless_opt_2[];
extern const GeoLayout mia_Mouth1_opt_2_15[];
extern const GeoLayout mia_Mouth2_opt_2_15[];
extern const GeoLayout mia_Mouth3_opt_2_15[];
extern const GeoLayout mia_Mouth4_opt_2_15[];
extern const GeoLayout mia_Mouth5_opt_2_15[];
extern const GeoLayout mia_Mouth6_opt_2_15[];
extern const GeoLayout mia_Mouth7_opt_2_15[];
extern const GeoLayout mia_MaskArmature_opt_2[];
extern const GeoLayout mia_Left_Hand_Open_opt_2[];
extern const GeoLayout mia_Left_Hand_Peace_opt_2[];
extern const GeoLayout mia_Left_Hand_Open_opt_2_1[];
extern const GeoLayout mia_Right_Hand_Open_opt_2[];
extern const GeoLayout mia_Right_Hand_Peace_opt_2[];
extern const GeoLayout mia_Right_Hand_Cap_opt_2[];
extern const GeoLayout mia_Right_Hand_Wing_Cap_opt_2[];
extern const GeoLayout mia_geo_opt_2_2[];
extern const GeoLayout mia_Mouth1_opt_3[];
extern const GeoLayout mia_Mouth2_opt_3[];
extern const GeoLayout mia_Mouth3_opt_3[];
extern const GeoLayout mia_Mouth4_opt_3[];
extern const GeoLayout mia_Mouth5_opt_3[];
extern const GeoLayout mia_Mouth6_opt_3[];
extern const GeoLayout mia_Mouth7_opt_3[];
extern const GeoLayout mia_Mouth1_opt_3_opt_1[];
extern const GeoLayout mia_Mouth2_opt_3_opt_1[];
extern const GeoLayout mia_Mouth3_opt_3_opt_1[];
extern const GeoLayout mia_Mouth4_opt_3_opt_1[];
extern const GeoLayout mia_Mouth5_opt_3_opt_1[];
extern const GeoLayout mia_Mouth6_opt_3_opt_1[];
extern const GeoLayout mia_Mouth7_opt_3_opt_1[];
extern const GeoLayout mia_geo_opt_3_opt_3_opt_1[];
extern const GeoLayout mia_Mouth1_opt_3_opt_2[];
extern const GeoLayout mia_Mouth2_opt_3_opt_2[];
extern const GeoLayout mia_Mouth3_opt_3_opt_2[];
extern const GeoLayout mia_Mouth4_opt_3_opt_2[];
extern const GeoLayout mia_Mouth5_opt_3_opt_2[];
extern const GeoLayout mia_Mouth6_opt_3_opt_2[];
extern const GeoLayout mia_Mouth7_opt_3_opt_2[];
extern const GeoLayout mia_geo_opt_3_opt_3_opt_2[];
extern const GeoLayout mia_Head_Left_opt_3[];
extern const GeoLayout mia_Mouth1_opt_3_1[];
extern const GeoLayout mia_Mouth2_opt_3_1[];
extern const GeoLayout mia_Mouth3_opt_3_1[];
extern const GeoLayout mia_Mouth4_opt_3_1[];
extern const GeoLayout mia_Mouth5_opt_3_1[];
extern const GeoLayout mia_Mouth6_opt_3_1[];
extern const GeoLayout mia_Mouth7_opt_3_1[];
extern const GeoLayout mia_Head_Right_opt_3[];
extern const GeoLayout mia_Mouth1_opt_3_2[];
extern const GeoLayout mia_Mouth2_opt_3_2[];
extern const GeoLayout mia_Mouth3_opt_3_2[];
extern const GeoLayout mia_Mouth4_opt_3_2[];
extern const GeoLayout mia_Mouth5_opt_3_2[];
extern const GeoLayout mia_Mouth6_opt_3_2[];
extern const GeoLayout mia_Mouth7_opt_3_2[];
extern const GeoLayout mia_Head_Up_opt_3[];
extern const GeoLayout mia_Mouth1_opt_3_3[];
extern const GeoLayout mia_Mouth2_opt_3_3[];
extern const GeoLayout mia_Mouth3_opt_3_3[];
extern const GeoLayout mia_Mouth4_opt_3_3[];
extern const GeoLayout mia_Mouth5_opt_3_3[];
extern const GeoLayout mia_Mouth6_opt_3_3[];
extern const GeoLayout mia_Mouth7_opt_3_3[];
extern const GeoLayout mia_Head_Down_opt_3[];
extern const GeoLayout mia_Mouth1_opt_3_4[];
extern const GeoLayout mia_Mouth2_opt_3_4[];
extern const GeoLayout mia_Mouth3_opt_3_4[];
extern const GeoLayout mia_Mouth4_opt_3_4[];
extern const GeoLayout mia_Mouth5_opt_3_4[];
extern const GeoLayout mia_Mouth6_opt_3_4[];
extern const GeoLayout mia_Mouth7_opt_3_4[];
extern const GeoLayout mia_Head_Dead_opt_3[];
extern const GeoLayout mia_Head_Extra1_opt_3[];
extern const GeoLayout mia_Mouth1_opt_3_5[];
extern const GeoLayout mia_Mouth2_opt_3_5[];
extern const GeoLayout mia_Mouth3_opt_3_5[];
extern const GeoLayout mia_Mouth4_opt_3_5[];
extern const GeoLayout mia_Mouth5_opt_3_5[];
extern const GeoLayout mia_Mouth6_opt_3_5[];
extern const GeoLayout mia_Mouth7_opt_3_5[];
extern const GeoLayout mia_Head_Extra2_opt_3[];
extern const GeoLayout mia_Mouth1_opt_3_6[];
extern const GeoLayout mia_Mouth2_opt_3_6[];
extern const GeoLayout mia_Mouth3_opt_3_6[];
extern const GeoLayout mia_Mouth4_opt_3_6[];
extern const GeoLayout mia_Mouth5_opt_3_6[];
extern const GeoLayout mia_Mouth6_opt_3_6[];
extern const GeoLayout mia_Mouth7_opt_3_6[];
extern const GeoLayout mia_Capless_Head_opt_3[];
extern const GeoLayout mia_Mouth1_opt_3_7[];
extern const GeoLayout mia_Mouth2_opt_3_7[];
extern const GeoLayout mia_Mouth3_opt_3_7[];
extern const GeoLayout mia_Mouth4_opt_3_7[];
extern const GeoLayout mia_Mouth5_opt_3_7[];
extern const GeoLayout mia_Mouth6_opt_3_7[];
extern const GeoLayout mia_Mouth7_opt_3_7[];
extern const GeoLayout mia_geo_opt_1_1_opt_3[];
extern const GeoLayout mia_Mouth1_opt_1_1_opt_3[];
extern const GeoLayout mia_Mouth2_opt_1_1_opt_3[];
extern const GeoLayout mia_Mouth3_opt_1_1_opt_3[];
extern const GeoLayout mia_Mouth4_opt_1_1_opt_3[];
extern const GeoLayout mia_Mouth5_opt_1_1_opt_3[];
extern const GeoLayout mia_Mouth6_opt_1_1_opt_3[];
extern const GeoLayout mia_Mouth7_opt_1_1_opt_3[];
extern const GeoLayout mia_geo_opt_2_1_opt_3[];
extern const GeoLayout mia_Mouth1_opt_2_1_opt_3[];
extern const GeoLayout mia_Mouth2_opt_2_1_opt_3[];
extern const GeoLayout mia_Mouth3_opt_2_1_opt_3[];
extern const GeoLayout mia_Mouth4_opt_2_1_opt_3[];
extern const GeoLayout mia_Mouth5_opt_2_1_opt_3[];
extern const GeoLayout mia_Mouth6_opt_2_1_opt_3[];
extern const GeoLayout mia_Mouth7_opt_2_1_opt_3[];
extern const GeoLayout mia_Capless_Head_Switch_Option_Capless_Head_Left_opt_3[];
extern const GeoLayout mia_Mouth1_opt_3_8[];
extern const GeoLayout mia_Mouth2_opt_3_8[];
extern const GeoLayout mia_Mouth3_opt_3_8[];
extern const GeoLayout mia_Mouth4_opt_3_8[];
extern const GeoLayout mia_Mouth5_opt_3_8[];
extern const GeoLayout mia_Mouth6_opt_3_8[];
extern const GeoLayout mia_Mouth7_opt_3_8[];
extern const GeoLayout mia_Capless_Head_Switch_Option_Capless_Head_Right_opt_3[];
extern const GeoLayout mia_Mouth1_opt_3_9[];
extern const GeoLayout mia_Mouth2_opt_3_9[];
extern const GeoLayout mia_Mouth3_opt_3_9[];
extern const GeoLayout mia_Mouth4_opt_3_9[];
extern const GeoLayout mia_Mouth5_opt_3_9[];
extern const GeoLayout mia_Mouth6_opt_3_9[];
extern const GeoLayout mia_Mouth7_opt_3_9[];
extern const GeoLayout mia_Capless_Head_Switch_Option_Capless_Head_Up_opt_3[];
extern const GeoLayout mia_Mouth1_opt_3_10[];
extern const GeoLayout mia_Mouth2_opt_3_10[];
extern const GeoLayout mia_Mouth3_opt_3_10[];
extern const GeoLayout mia_Mouth4_opt_3_10[];
extern const GeoLayout mia_Mouth5_opt_3_10[];
extern const GeoLayout mia_Mouth6_opt_3_10[];
extern const GeoLayout mia_Mouth7_opt_3_10[];
extern const GeoLayout mia_Capless_Head_Switch_Option_Capless_Head_Down_opt_3[];
extern const GeoLayout mia_Mouth1_opt_3_11[];
extern const GeoLayout mia_Mouth2_opt_3_11[];
extern const GeoLayout mia_Mouth3_opt_3_11[];
extern const GeoLayout mia_Mouth4_opt_3_11[];
extern const GeoLayout mia_Mouth5_opt_3_11[];
extern const GeoLayout mia_Mouth6_opt_3_11[];
extern const GeoLayout mia_Mouth7_opt_3_11[];
extern const GeoLayout mia_Capless_Head_Switch_Option_Capless_Head_Dead_opt_3[];
extern const GeoLayout mia_Capless_Head_Switch_Option_Head_Extra1_Capless_opt_3[];
extern const GeoLayout mia_Mouth1_opt_3_12[];
extern const GeoLayout mia_Mouth2_opt_3_12[];
extern const GeoLayout mia_Mouth3_opt_3_12[];
extern const GeoLayout mia_Mouth4_opt_3_12[];
extern const GeoLayout mia_Mouth5_opt_3_12[];
extern const GeoLayout mia_Mouth6_opt_3_12[];
extern const GeoLayout mia_Mouth7_opt_3_12[];
extern const GeoLayout mia_Capless_Head_Switch_Option_Head_Extra2_Capless_opt_3[];
extern const GeoLayout mia_Mouth1_opt_3_13[];
extern const GeoLayout mia_Mouth2_opt_3_13[];
extern const GeoLayout mia_Mouth3_opt_3_13[];
extern const GeoLayout mia_Mouth4_opt_3_13[];
extern const GeoLayout mia_Mouth5_opt_3_13[];
extern const GeoLayout mia_Mouth6_opt_3_13[];
extern const GeoLayout mia_Mouth7_opt_3_13[];
extern const GeoLayout mia_MaskArmature_opt_3[];
extern const GeoLayout mia_Left_Hand_Open_opt_3[];
extern const GeoLayout mia_Left_Hand_Peace_opt_3[];
extern const GeoLayout mia_Left_Hand_Open_opt_3_1[];
extern const GeoLayout mia_Right_Hand_Open_opt_3[];
extern const GeoLayout mia_Right_Hand_Peace_opt_3[];
extern const GeoLayout mia_Right_Hand_Cap_opt_3[];
extern const GeoLayout mia_Right_Hand_Wing_Cap_opt_3[];
extern const GeoLayout mia_geo_opt_3[];
extern const GeoLayout mia_geo[];
extern Lights1 mia_Overalls_lights;
extern Lights1 mia_Skin_lights;
extern Lights1 mia_Shirt_lights;
extern Lights1 mia_Hair_lights;
extern Lights1 mia_Cap_lights;
extern Lights1 mia_Eye1_lights;
extern Lights1 mia_Mouth_lights;
extern Lights1 mia_Mouth_1_lights;
extern Lights1 mia_Mouth_2_lights;
extern Lights1 mia_Mouth_3_lights;
extern Lights1 mia_Mouth_4_lights;
extern Lights1 mia_Mouth_5_lights;
extern Lights1 mia_Mouth_6_lights;
extern Lights1 mia_Mouth_7_lights;
extern Lights1 mia_Eye_left_lights;
extern Lights1 mia_Eye_Up_lights;
extern Lights1 mia_Eye_Down_lights;
extern Lights1 mia_Eye_Dead_lights;
extern Lights1 mia_Mouth___lights;
extern Lights1 mia_Eye_Happy_lights;
extern Lights1 mia_Eye_Help_lights;
extern Lights1 mia_Mask1_lights;
extern Lights1 mia_Mask2_lights;
extern Lights1 mia_Cap_Inside_lights;
extern Lights1 mia_Shoes_lights;
extern Lights1 mia_ShoesBottom_lights;
extern Lights1 mia_Eye_Half_lights;
extern Lights1 mia_Eye_Closed_lights;
extern Lights1 mia_Metal__METAL__lights;
extern u8 mia_Button_rgba16[];
extern u8 mia_Logo_rgba16[];
extern u8 mia_Eyes1_rgba16[];
extern u8 mia_mouth1_rgba16[];
extern u8 mia_mouth2_rgba16[];
extern u8 mia_mouth3_rgba16[];
extern u8 mia_mouth4_rgba16[];
extern u8 mia_mouth6_rgba16[];
extern u8 mia_mouth5_rgba16[];
extern u8 mia_mouth7_rgba16[];
extern u8 mia_mouth8_rgba16[];
extern u8 mia_Eyes5_rgba16[];
extern u8 mia_Eyes6_rgba16[];
extern u8 mia_Eyes4_rgba16[];
extern u8 mia_Eyes7_rgba16[];
extern u8 mia_Eyes8_rgba16[];
extern u8 mia_Eyes9_rgba16[];
extern u8 mia_mia_Wing1_rgba16[];
extern u8 mia_Eyes2_rgba16[];
extern u8 mia_Eyes3_rgba16[];
extern u8 mia_metal_mariokart_rgba16[];
extern u8 mia_Metal_Light_rgba16_rgba16[];
extern Vtx mia_Butt_mesh_layer_1_vtx_0[14];
extern Gfx mia_Butt_mesh_layer_1_tri_0[];
extern Vtx mia_Torso_mesh_layer_1_vtx_0[31];
extern Gfx mia_Torso_mesh_layer_1_tri_0[];
extern Vtx mia_Torso_mesh_layer_1_vtx_1[8];
extern Gfx mia_Torso_mesh_layer_1_tri_1[];
extern Vtx mia_Torso_mesh_layer_1_vtx_2[20];
extern Gfx mia_Torso_mesh_layer_1_tri_2[];
extern Vtx mia_Head_DL_mesh_layer_1_vtx_0[24];
extern Gfx mia_Head_DL_mesh_layer_1_tri_0[];
extern Vtx mia_Head_DL_mesh_layer_1_vtx_1[50];
extern Gfx mia_Head_DL_mesh_layer_1_tri_1[];
extern Vtx mia_Head_DL_mesh_layer_1_vtx_2[36];
extern Gfx mia_Head_DL_mesh_layer_1_tri_2[];
extern Vtx mia_Head_DL_mesh_layer_1_vtx_3[8];
extern Gfx mia_Head_DL_mesh_layer_1_tri_3[];
extern Vtx mia_Head_DL_mesh_layer_1_vtx_4[8];
extern Gfx mia_Head_DL_mesh_layer_1_tri_4[];
extern Vtx mia_Mouth_DL_mesh_layer_1_vtx_0[6];
extern Gfx mia_Mouth_DL_mesh_layer_1_tri_0[];
extern Vtx mia_Mouth_Switch_Option_MouthDL_mesh_layer_1_vtx_0[6];
extern Gfx mia_Mouth_Switch_Option_MouthDL_mesh_layer_1_tri_0[];
extern Vtx mia_Mouth_Switch_Option_Mouth2DL_mesh_layer_1_vtx_0[6];
extern Gfx mia_Mouth_Switch_Option_Mouth2DL_mesh_layer_1_tri_0[];
extern Vtx mia_Mouth_Switch_Option_Mouth3DL_mesh_layer_1_vtx_0[6];
extern Gfx mia_Mouth_Switch_Option_Mouth3DL_mesh_layer_1_tri_0[];
extern Vtx mia_Mouth_Switch_Option_Mouth4DL_mesh_layer_1_vtx_0[6];
extern Gfx mia_Mouth_Switch_Option_Mouth4DL_mesh_layer_1_tri_0[];
extern Vtx mia_Mouth_Switch_Option_Mouth5DL_mesh_layer_1_vtx_0[6];
extern Gfx mia_Mouth_Switch_Option_Mouth5DL_mesh_layer_1_tri_0[];
extern Vtx mia_Mouth_Switch_Option_Mouth6DL_mesh_layer_1_vtx_0[6];
extern Gfx mia_Mouth_Switch_Option_Mouth6DL_mesh_layer_1_tri_0[];
extern Vtx mia_Mouth_Switch_Option_Mouth7DL_mesh_layer_1_vtx_0[6];
extern Gfx mia_Mouth_Switch_Option_Mouth7DL_mesh_layer_1_tri_0[];
extern Vtx mia_Head_Left_Switch_Option_Head_Left_DL_mesh_layer_1_vtx_0[24];
extern Gfx mia_Head_Left_Switch_Option_Head_Left_DL_mesh_layer_1_tri_0[];
extern Vtx mia_Head_Left_Switch_Option_Head_Left_DL_mesh_layer_1_vtx_1[50];
extern Gfx mia_Head_Left_Switch_Option_Head_Left_DL_mesh_layer_1_tri_1[];
extern Vtx mia_Head_Left_Switch_Option_Head_Left_DL_mesh_layer_1_vtx_2[36];
extern Gfx mia_Head_Left_Switch_Option_Head_Left_DL_mesh_layer_1_tri_2[];
extern Vtx mia_Head_Left_Switch_Option_Head_Left_DL_mesh_layer_1_vtx_3[8];
extern Gfx mia_Head_Left_Switch_Option_Head_Left_DL_mesh_layer_1_tri_3[];
extern Vtx mia_Head_Left_Switch_Option_Head_Left_DL_mesh_layer_1_vtx_4[8];
extern Gfx mia_Head_Left_Switch_Option_Head_Left_DL_mesh_layer_1_tri_4[];
extern Vtx mia_Head_Left_Switch_Option_Mouth_DL_mesh_layer_1_vtx_0[6];
extern Gfx mia_Head_Left_Switch_Option_Mouth_DL_mesh_layer_1_tri_0[];
extern Vtx mia_Head_Right_Switch_Option_Head_Right_DL_mesh_layer_1_vtx_0[24];
extern Gfx mia_Head_Right_Switch_Option_Head_Right_DL_mesh_layer_1_tri_0[];
extern Vtx mia_Head_Right_Switch_Option_Head_Right_DL_mesh_layer_1_vtx_1[50];
extern Gfx mia_Head_Right_Switch_Option_Head_Right_DL_mesh_layer_1_tri_1[];
extern Vtx mia_Head_Right_Switch_Option_Head_Right_DL_mesh_layer_1_vtx_2[36];
extern Gfx mia_Head_Right_Switch_Option_Head_Right_DL_mesh_layer_1_tri_2[];
extern Vtx mia_Head_Right_Switch_Option_Head_Right_DL_mesh_layer_1_vtx_3[8];
extern Gfx mia_Head_Right_Switch_Option_Head_Right_DL_mesh_layer_1_tri_3[];
extern Vtx mia_Head_Right_Switch_Option_Head_Right_DL_mesh_layer_1_vtx_4[8];
extern Gfx mia_Head_Right_Switch_Option_Head_Right_DL_mesh_layer_1_tri_4[];
extern Vtx mia_Head_Right_Switch_Option_Mouth_DL_mesh_layer_1_vtx_0[6];
extern Gfx mia_Head_Right_Switch_Option_Mouth_DL_mesh_layer_1_tri_0[];
extern Vtx mia_Head_Up_Switch_Option_Head_Up_DL_mesh_layer_1_vtx_0[24];
extern Gfx mia_Head_Up_Switch_Option_Head_Up_DL_mesh_layer_1_tri_0[];
extern Vtx mia_Head_Up_Switch_Option_Head_Up_DL_mesh_layer_1_vtx_1[50];
extern Gfx mia_Head_Up_Switch_Option_Head_Up_DL_mesh_layer_1_tri_1[];
extern Vtx mia_Head_Up_Switch_Option_Head_Up_DL_mesh_layer_1_vtx_2[36];
extern Gfx mia_Head_Up_Switch_Option_Head_Up_DL_mesh_layer_1_tri_2[];
extern Vtx mia_Head_Up_Switch_Option_Head_Up_DL_mesh_layer_1_vtx_3[12];
extern Gfx mia_Head_Up_Switch_Option_Head_Up_DL_mesh_layer_1_tri_3[];
extern Vtx mia_Head_Up_Switch_Option_Mouth_DL_mesh_layer_1_vtx_0[6];
extern Gfx mia_Head_Up_Switch_Option_Mouth_DL_mesh_layer_1_tri_0[];
extern Vtx mia_Head_Down_Switch_Option_Head_Down_DL_mesh_layer_1_vtx_0[24];
extern Gfx mia_Head_Down_Switch_Option_Head_Down_DL_mesh_layer_1_tri_0[];
extern Vtx mia_Head_Down_Switch_Option_Head_Down_DL_mesh_layer_1_vtx_1[50];
extern Gfx mia_Head_Down_Switch_Option_Head_Down_DL_mesh_layer_1_tri_1[];
extern Vtx mia_Head_Down_Switch_Option_Head_Down_DL_mesh_layer_1_vtx_2[36];
extern Gfx mia_Head_Down_Switch_Option_Head_Down_DL_mesh_layer_1_tri_2[];
extern Vtx mia_Head_Down_Switch_Option_Head_Down_DL_mesh_layer_1_vtx_3[12];
extern Gfx mia_Head_Down_Switch_Option_Head_Down_DL_mesh_layer_1_tri_3[];
extern Vtx mia_Head_Down_Switch_Option_Mouth_DL_mesh_layer_1_vtx_0[6];
extern Gfx mia_Head_Down_Switch_Option_Mouth_DL_mesh_layer_1_tri_0[];
extern Vtx mia_Head_Dead_Switch_Option_Head_Dead_DL_mesh_layer_1_vtx_0[24];
extern Gfx mia_Head_Dead_Switch_Option_Head_Dead_DL_mesh_layer_1_tri_0[];
extern Vtx mia_Head_Dead_Switch_Option_Head_Dead_DL_mesh_layer_1_vtx_1[50];
extern Gfx mia_Head_Dead_Switch_Option_Head_Dead_DL_mesh_layer_1_tri_1[];
extern Vtx mia_Head_Dead_Switch_Option_Head_Dead_DL_mesh_layer_1_vtx_2[36];
extern Gfx mia_Head_Dead_Switch_Option_Head_Dead_DL_mesh_layer_1_tri_2[];
extern Vtx mia_Head_Dead_Switch_Option_Head_Dead_DL_mesh_layer_1_vtx_3[11];
extern Gfx mia_Head_Dead_Switch_Option_Head_Dead_DL_mesh_layer_1_tri_3[];
extern Vtx mia_Head_Dead_Switch_Option_Head_Dead_DL_mesh_layer_1_vtx_4[6];
extern Gfx mia_Head_Dead_Switch_Option_Head_Dead_DL_mesh_layer_1_tri_4[];
extern Vtx mia_Head_Switch_Option_Head_Extra1_DL_mesh_layer_1_vtx_0[24];
extern Gfx mia_Head_Switch_Option_Head_Extra1_DL_mesh_layer_1_tri_0[];
extern Vtx mia_Head_Switch_Option_Head_Extra1_DL_mesh_layer_1_vtx_1[50];
extern Gfx mia_Head_Switch_Option_Head_Extra1_DL_mesh_layer_1_tri_1[];
extern Vtx mia_Head_Switch_Option_Head_Extra1_DL_mesh_layer_1_vtx_2[36];
extern Gfx mia_Head_Switch_Option_Head_Extra1_DL_mesh_layer_1_tri_2[];
extern Vtx mia_Head_Switch_Option_Head_Extra1_DL_mesh_layer_1_vtx_3[12];
extern Gfx mia_Head_Switch_Option_Head_Extra1_DL_mesh_layer_1_tri_3[];
extern Vtx mia_Head_Switch_Option_Mouth_DL2_mesh_layer_1_vtx_0[6];
extern Gfx mia_Head_Switch_Option_Mouth_DL2_mesh_layer_1_tri_0[];
extern Vtx mia_Head_Switch_Option_Head_Extra2_DL_mesh_layer_1_vtx_0[24];
extern Gfx mia_Head_Switch_Option_Head_Extra2_DL_mesh_layer_1_tri_0[];
extern Vtx mia_Head_Switch_Option_Head_Extra2_DL_mesh_layer_1_vtx_1[50];
extern Gfx mia_Head_Switch_Option_Head_Extra2_DL_mesh_layer_1_tri_1[];
extern Vtx mia_Head_Switch_Option_Head_Extra2_DL_mesh_layer_1_vtx_2[36];
extern Gfx mia_Head_Switch_Option_Head_Extra2_DL_mesh_layer_1_tri_2[];
extern Vtx mia_Head_Switch_Option_Head_Extra2_DL_mesh_layer_1_vtx_3[12];
extern Gfx mia_Head_Switch_Option_Head_Extra2_DL_mesh_layer_1_tri_3[];
extern Vtx mia_Head_Switch_Option_Mouth_DL1_mesh_layer_1_vtx_0[6];
extern Gfx mia_Head_Switch_Option_Mouth_DL1_mesh_layer_1_tri_0[];
extern Vtx mia_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_vtx_0[24];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_tri_0[];
extern Vtx mia_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_vtx_1[74];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_tri_1[];
extern Vtx mia_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_vtx_2[12];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_tri_2[];
extern Vtx mia_Capless_Head_Switch_Option_Mouth_DL_mesh_layer_1_vtx_0[6];
extern Gfx mia_Capless_Head_Switch_Option_Mouth_DL_mesh_layer_1_tri_0[];
extern Vtx mia_Capless_Head_Switch_Option_Capless_Head_Left_Switch_Option_Capless_Head_Left_DL_mesh_layer_1_vtx_0[24];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_Left_Switch_Option_Capless_Head_Left_DL_mesh_layer_1_tri_0[];
extern Vtx mia_Capless_Head_Switch_Option_Capless_Head_Left_Switch_Option_Capless_Head_Left_DL_mesh_layer_1_vtx_1[74];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_Left_Switch_Option_Capless_Head_Left_DL_mesh_layer_1_tri_1[];
extern Vtx mia_Capless_Head_Switch_Option_Capless_Head_Left_Switch_Option_Capless_Head_Left_DL_mesh_layer_1_vtx_2[8];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_Left_Switch_Option_Capless_Head_Left_DL_mesh_layer_1_tri_2[];
extern Vtx mia_Capless_Head_Switch_Option_Capless_Head_Left_Switch_Option_Capless_Head_Left_DL_mesh_layer_1_vtx_3[8];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_Left_Switch_Option_Capless_Head_Left_DL_mesh_layer_1_tri_3[];
extern Vtx mia_Capless_Head_Switch_Option_Capless_Head_Left_Switch_Option_Mouth_DL_mesh_layer_1_vtx_0[6];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_Left_Switch_Option_Mouth_DL_mesh_layer_1_tri_0[];
extern Vtx mia_Capless_Head_Switch_Option_Capless_Head_Right_Switch_Option_Capless_Head_Right_DL_mesh_layer_1_vtx_0[24];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_Right_Switch_Option_Capless_Head_Right_DL_mesh_layer_1_tri_0[];
extern Vtx mia_Capless_Head_Switch_Option_Capless_Head_Right_Switch_Option_Capless_Head_Right_DL_mesh_layer_1_vtx_1[74];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_Right_Switch_Option_Capless_Head_Right_DL_mesh_layer_1_tri_1[];
extern Vtx mia_Capless_Head_Switch_Option_Capless_Head_Right_Switch_Option_Capless_Head_Right_DL_mesh_layer_1_vtx_2[8];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_Right_Switch_Option_Capless_Head_Right_DL_mesh_layer_1_tri_2[];
extern Vtx mia_Capless_Head_Switch_Option_Capless_Head_Right_Switch_Option_Capless_Head_Right_DL_mesh_layer_1_vtx_3[8];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_Right_Switch_Option_Capless_Head_Right_DL_mesh_layer_1_tri_3[];
extern Vtx mia_Capless_Head_Switch_Option_Capless_Head_Right_Switch_Option_Mouth_DL_mesh_layer_1_vtx_0[6];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_Right_Switch_Option_Mouth_DL_mesh_layer_1_tri_0[];
extern Vtx mia_Capless_Head_Switch_Option_Capless_Head_Up_Switch_Option_Capless_Head_Up_DL_mesh_layer_1_vtx_0[24];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_Up_Switch_Option_Capless_Head_Up_DL_mesh_layer_1_tri_0[];
extern Vtx mia_Capless_Head_Switch_Option_Capless_Head_Up_Switch_Option_Capless_Head_Up_DL_mesh_layer_1_vtx_1[74];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_Up_Switch_Option_Capless_Head_Up_DL_mesh_layer_1_tri_1[];
extern Vtx mia_Capless_Head_Switch_Option_Capless_Head_Up_Switch_Option_Capless_Head_Up_DL_mesh_layer_1_vtx_2[12];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_Up_Switch_Option_Capless_Head_Up_DL_mesh_layer_1_tri_2[];
extern Vtx mia_Capless_Head_Switch_Option_Capless_Head_Up_Switch_Option_Mouth_DL_mesh_layer_1_vtx_0[6];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_Up_Switch_Option_Mouth_DL_mesh_layer_1_tri_0[];
extern Vtx mia_Capless_Head_Switch_Option_Capless_Head_Down_Switch_Option_Capless_Head_Down_DL_mesh_layer_1_vtx_0[24];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_Down_Switch_Option_Capless_Head_Down_DL_mesh_layer_1_tri_0[];
extern Vtx mia_Capless_Head_Switch_Option_Capless_Head_Down_Switch_Option_Capless_Head_Down_DL_mesh_layer_1_vtx_1[76];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_Down_Switch_Option_Capless_Head_Down_DL_mesh_layer_1_tri_1[];
extern Vtx mia_Capless_Head_Switch_Option_Capless_Head_Down_Switch_Option_Capless_Head_Down_DL_mesh_layer_1_vtx_2[12];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_Down_Switch_Option_Capless_Head_Down_DL_mesh_layer_1_tri_2[];
extern Vtx mia_Capless_Head_Switch_Option_Capless_Head_Down_Switch_Option_Mouth_DL_mesh_layer_1_vtx_0[6];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_Down_Switch_Option_Mouth_DL_mesh_layer_1_tri_0[];
extern Vtx mia_Capless_Head_Switch_Option_Capless_Head_Dead_Switch_Option_Capless_Head_Dead_DL_mesh_layer_1_vtx_0[24];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_Dead_Switch_Option_Capless_Head_Dead_DL_mesh_layer_1_tri_0[];
extern Vtx mia_Capless_Head_Switch_Option_Capless_Head_Dead_Switch_Option_Capless_Head_Dead_DL_mesh_layer_1_vtx_1[61];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_Dead_Switch_Option_Capless_Head_Dead_DL_mesh_layer_1_tri_1[];
extern Vtx mia_Capless_Head_Switch_Option_Capless_Head_Dead_Switch_Option_Capless_Head_Dead_DL_mesh_layer_1_vtx_2[11];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_Dead_Switch_Option_Capless_Head_Dead_DL_mesh_layer_1_tri_2[];
extern Vtx mia_Capless_Head_Switch_Option_Capless_Head_Dead_Switch_Option_Capless_Head_Dead_DL_mesh_layer_1_vtx_3[6];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_Dead_Switch_Option_Capless_Head_Dead_DL_mesh_layer_1_tri_3[];
extern Vtx mia_Capless_Head_Switch_Option_Head_Switch_Option_Head_Extra1_Capless_DL_mesh_layer_1_vtx_0[24];
extern Gfx mia_Capless_Head_Switch_Option_Head_Switch_Option_Head_Extra1_Capless_DL_mesh_layer_1_tri_0[];
extern Vtx mia_Capless_Head_Switch_Option_Head_Switch_Option_Head_Extra1_Capless_DL_mesh_layer_1_vtx_1[74];
extern Gfx mia_Capless_Head_Switch_Option_Head_Switch_Option_Head_Extra1_Capless_DL_mesh_layer_1_tri_1[];
extern Vtx mia_Capless_Head_Switch_Option_Head_Switch_Option_Head_Extra1_Capless_DL_mesh_layer_1_vtx_2[12];
extern Gfx mia_Capless_Head_Switch_Option_Head_Switch_Option_Head_Extra1_Capless_DL_mesh_layer_1_tri_2[];
extern Vtx mia_Capless_Head_Switch_Option_Head_Switch_Option_Mouth_DL2_mesh_layer_1_vtx_0[6];
extern Gfx mia_Capless_Head_Switch_Option_Head_Switch_Option_Mouth_DL2_mesh_layer_1_tri_0[];
extern Vtx mia_Capless_Head_Switch_Option_Head_Switch_Option_Head_Extra2_Capless_DL_mesh_layer_1_vtx_0[24];
extern Gfx mia_Capless_Head_Switch_Option_Head_Switch_Option_Head_Extra2_Capless_DL_mesh_layer_1_tri_0[];
extern Vtx mia_Capless_Head_Switch_Option_Head_Switch_Option_Head_Extra2_Capless_DL_mesh_layer_1_vtx_1[76];
extern Gfx mia_Capless_Head_Switch_Option_Head_Switch_Option_Head_Extra2_Capless_DL_mesh_layer_1_tri_1[];
extern Vtx mia_Capless_Head_Switch_Option_Head_Switch_Option_Head_Extra2_Capless_DL_mesh_layer_1_vtx_2[12];
extern Gfx mia_Capless_Head_Switch_Option_Head_Switch_Option_Head_Extra2_Capless_DL_mesh_layer_1_tri_2[];
extern Vtx mia_Capless_Head_Switch_Option_Head_Switch_Option_Mouth_DL1_mesh_layer_1_vtx_0[6];
extern Gfx mia_Capless_Head_Switch_Option_Head_Switch_Option_Mouth_DL1_mesh_layer_1_tri_0[];
extern Vtx mia_Hair_1_mesh_layer_1_vtx_0[24];
extern Gfx mia_Hair_1_mesh_layer_1_tri_0[];
extern Vtx mia_Left_Wing_DL_mesh_layer_4_vtx_0[4];
extern Gfx mia_Left_Wing_DL_mesh_layer_4_tri_0[];
extern Vtx mia_MaskSwitchOption_MaskDL_mesh_layer_1_vtx_0[18];
extern Gfx mia_MaskSwitchOption_MaskDL_mesh_layer_1_tri_0[];
extern Vtx mia_MaskSwitchOption_MaskDL_mesh_layer_6_vtx_0[9];
extern Gfx mia_MaskSwitchOption_MaskDL_mesh_layer_6_tri_0[];
extern Vtx mia_Right_Wing_DL_mesh_layer_4_vtx_0[4];
extern Gfx mia_Right_Wing_DL_mesh_layer_4_tri_0[];
extern Vtx mia_Left_Arm_Color_mesh_layer_1_vtx_0[19];
extern Gfx mia_Left_Arm_Color_mesh_layer_1_tri_0[];
extern Vtx mia_Left_Forearm_mesh_layer_1_vtx_0[14];
extern Gfx mia_Left_Forearm_mesh_layer_1_tri_0[];
extern Vtx mia_Left_Hand_DL_mesh_layer_1_vtx_0[10];
extern Gfx mia_Left_Hand_DL_mesh_layer_1_tri_0[];
extern Vtx mia_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1_vtx_0[14];
extern Gfx mia_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1_tri_0[];
extern Vtx mia_Left_Hand_Peace_Switch_Option_Left_Hand_Peace_mesh_layer_1_vtx_0[14];
extern Gfx mia_Left_Hand_Peace_Switch_Option_Left_Hand_Peace_mesh_layer_1_tri_0[];
extern Vtx mia_Right_Arm_Color_mesh_layer_1_vtx_0[19];
extern Gfx mia_Right_Arm_Color_mesh_layer_1_tri_0[];
extern Vtx mia_Right_Forearm_mesh_layer_1_vtx_0[14];
extern Gfx mia_Right_Forearm_mesh_layer_1_tri_0[];
extern Vtx mia_Right_Hand_DL_mesh_layer_1_vtx_0[10];
extern Gfx mia_Right_Hand_DL_mesh_layer_1_tri_0[];
extern Vtx mia_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1_vtx_0[14];
extern Gfx mia_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1_tri_0[];
extern Vtx mia_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1_vtx_0[14];
extern Gfx mia_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1_tri_0[];
extern Vtx mia_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1_vtx_0[10];
extern Gfx mia_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1_tri_0[];
extern Vtx mia_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1_vtx_1[36];
extern Gfx mia_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1_tri_1[];
extern Vtx mia_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1_vtx_2[8];
extern Gfx mia_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1_tri_2[];
extern Vtx mia_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1_vtx_0[10];
extern Gfx mia_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1_tri_0[];
extern Vtx mia_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1_vtx_1[36];
extern Gfx mia_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1_tri_1[];
extern Vtx mia_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1_vtx_2[8];
extern Gfx mia_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1_tri_2[];
extern Vtx mia_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_4_vtx_0[8];
extern Gfx mia_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_4_tri_0[];
extern Vtx mia_Left_Thigh_Color_mesh_layer_1_vtx_0[10];
extern Gfx mia_Left_Thigh_Color_mesh_layer_1_tri_0[];
extern Vtx mia_Left_Leg_mesh_layer_1_vtx_0[10];
extern Gfx mia_Left_Leg_mesh_layer_1_tri_0[];
extern Vtx mia_Left_Shoe_mesh_layer_1_vtx_0[11];
extern Gfx mia_Left_Shoe_mesh_layer_1_tri_0[];
extern Vtx mia_Left_Shoe_mesh_layer_1_vtx_1[6];
extern Gfx mia_Left_Shoe_mesh_layer_1_tri_1[];
extern Vtx mia_Right_Thigh_Color_mesh_layer_1_vtx_0[10];
extern Gfx mia_Right_Thigh_Color_mesh_layer_1_tri_0[];
extern Vtx mia_Right_Leg_mesh_layer_1_vtx_0[10];
extern Gfx mia_Right_Leg_mesh_layer_1_tri_0[];
extern Vtx mia_Right_Shoe_DL_mesh_layer_1_vtx_0[11];
extern Gfx mia_Right_Shoe_DL_mesh_layer_1_tri_0[];
extern Vtx mia_Right_Shoe_DL_mesh_layer_1_vtx_1[6];
extern Gfx mia_Right_Shoe_DL_mesh_layer_1_tri_1[];
extern Gfx mat_mia_Overalls[];
extern Gfx mat_revert_mia_Overalls[];
extern Gfx mat_mia_Skin[];
extern Gfx mat_revert_mia_Skin[];
extern Gfx mat_mia_Shirt[];
extern Gfx mat_revert_mia_Shirt[];
extern Gfx mat_mia_Hair[];
extern Gfx mat_revert_mia_Hair[];
extern Gfx mat_mia_Cap[];
extern Gfx mat_revert_mia_Cap[];
extern Gfx mat_mia_Eye1[];
extern Gfx mat_revert_mia_Eye1[];
extern Gfx mat_mia_Mouth[];
extern Gfx mat_revert_mia_Mouth[];
extern Gfx mat_mia_Mouth_1[];
extern Gfx mat_revert_mia_Mouth_1[];
extern Gfx mat_mia_Mouth_2[];
extern Gfx mat_revert_mia_Mouth_2[];
extern Gfx mat_mia_Mouth_3[];
extern Gfx mat_revert_mia_Mouth_3[];
extern Gfx mat_mia_Mouth_4[];
extern Gfx mat_revert_mia_Mouth_4[];
extern Gfx mat_mia_Mouth_5[];
extern Gfx mat_revert_mia_Mouth_5[];
extern Gfx mat_mia_Mouth_6[];
extern Gfx mat_revert_mia_Mouth_6[];
extern Gfx mat_mia_Mouth_7[];
extern Gfx mat_revert_mia_Mouth_7[];
extern Gfx mat_mia_Eye_left[];
extern Gfx mat_revert_mia_Eye_left[];
extern Gfx mat_mia_Eye_Up[];
extern Gfx mat_revert_mia_Eye_Up[];
extern Gfx mat_mia_Eye_Down[];
extern Gfx mat_revert_mia_Eye_Down[];
extern Gfx mat_mia_Eye_Dead[];
extern Gfx mat_revert_mia_Eye_Dead[];
extern Gfx mat_mia_Mouth__[];
extern Gfx mat_revert_mia_Mouth__[];
extern Gfx mat_mia_Eye_Happy[];
extern Gfx mat_revert_mia_Eye_Happy[];
extern Gfx mat_mia_Eye_Help[];
extern Gfx mat_revert_mia_Eye_Help[];
extern Gfx mat_mia_Wings[];
extern Gfx mat_revert_mia_Wings[];
extern Gfx mat_mia_Mask1[];
extern Gfx mat_revert_mia_Mask1[];
extern Gfx mat_mia_Mask2[];
extern Gfx mat_revert_mia_Mask2[];
extern Gfx mat_mia_Cap_Inside[];
extern Gfx mat_revert_mia_Cap_Inside[];
extern Gfx mat_mia_Shoes[];
extern Gfx mat_revert_mia_Shoes[];
extern Gfx mat_mia_ShoesBottom[];
extern Gfx mat_revert_mia_ShoesBottom[];
extern Gfx mat_mia_Eye_Half[];
extern Gfx mat_revert_mia_Eye_Half[];
extern Gfx mat_mia_Eye_Closed[];
extern Gfx mat_revert_mia_Eye_Closed[];
extern Gfx mat_mia_Metal__METAL_[];
extern Gfx mat_revert_mia_Metal__METAL_[];
extern Gfx mia_Butt_mesh_layer_1[];
extern Gfx mia_Butt_mesh_layer_1_opt_2[];
extern Gfx mia_Torso_mesh_layer_1[];
extern Gfx mia_Torso_mesh_layer_1_opt_2[];
extern Gfx mia_Head_DL_mesh_layer_1[];
extern Gfx mia_Head_DL_mesh_layer_1_opt_1[];
extern Gfx mia_Head_DL_mesh_layer_1_opt_2[];
extern Gfx mia_Head_DL_mesh_layer_1_opt_2_0[];
extern Gfx mia_Mouth_DL_mesh_layer_1[];
extern Gfx mia_Mouth_DL_mesh_layer_1_opt_2[];
extern Gfx mia_Mouth_Switch_Option_MouthDL_mesh_layer_1[];
extern Gfx mia_Mouth_Switch_Option_MouthDL_mesh_layer_1_opt_2[];
extern Gfx mia_Mouth_Switch_Option_Mouth2DL_mesh_layer_1[];
extern Gfx mia_Mouth_Switch_Option_Mouth2DL_mesh_layer_1_opt_2[];
extern Gfx mia_Mouth_Switch_Option_Mouth3DL_mesh_layer_1[];
extern Gfx mia_Mouth_Switch_Option_Mouth3DL_mesh_layer_1_opt_2[];
extern Gfx mia_Mouth_Switch_Option_Mouth4DL_mesh_layer_1[];
extern Gfx mia_Mouth_Switch_Option_Mouth4DL_mesh_layer_1_opt_2[];
extern Gfx mia_Mouth_Switch_Option_Mouth5DL_mesh_layer_1[];
extern Gfx mia_Mouth_Switch_Option_Mouth5DL_mesh_layer_1_opt_2[];
extern Gfx mia_Mouth_Switch_Option_Mouth6DL_mesh_layer_1[];
extern Gfx mia_Mouth_Switch_Option_Mouth6DL_mesh_layer_1_opt_2[];
extern Gfx mia_Mouth_Switch_Option_Mouth7DL_mesh_layer_1[];
extern Gfx mia_Mouth_Switch_Option_Mouth7DL_mesh_layer_1_opt_2[];
extern Gfx mia_Head_Left_Switch_Option_Head_Left_DL_mesh_layer_1[];
extern Gfx mia_Head_Left_Switch_Option_Head_Left_DL_mesh_layer_1_opt_2[];
extern Gfx mia_Head_Left_Switch_Option_Mouth_DL_mesh_layer_1[];
extern Gfx mia_Head_Left_Switch_Option_Mouth_DL_mesh_layer_1_opt_2[];
extern Gfx mia_Head_Right_Switch_Option_Head_Right_DL_mesh_layer_1[];
extern Gfx mia_Head_Right_Switch_Option_Head_Right_DL_mesh_layer_1_opt_2[];
extern Gfx mia_Head_Right_Switch_Option_Mouth_DL_mesh_layer_1[];
extern Gfx mia_Head_Right_Switch_Option_Mouth_DL_mesh_layer_1_opt_2[];
extern Gfx mia_Head_Up_Switch_Option_Head_Up_DL_mesh_layer_1[];
extern Gfx mia_Head_Up_Switch_Option_Head_Up_DL_mesh_layer_1_opt_2[];
extern Gfx mia_Head_Up_Switch_Option_Mouth_DL_mesh_layer_1[];
extern Gfx mia_Head_Up_Switch_Option_Mouth_DL_mesh_layer_1_opt_2[];
extern Gfx mia_Head_Down_Switch_Option_Head_Down_DL_mesh_layer_1[];
extern Gfx mia_Head_Down_Switch_Option_Head_Down_DL_mesh_layer_1_opt_2[];
extern Gfx mia_Head_Down_Switch_Option_Mouth_DL_mesh_layer_1[];
extern Gfx mia_Head_Down_Switch_Option_Mouth_DL_mesh_layer_1_opt_2[];
extern Gfx mia_Head_Dead_Switch_Option_Head_Dead_DL_mesh_layer_1[];
extern Gfx mia_Head_Dead_Switch_Option_Head_Dead_DL_mesh_layer_1_opt_2[];
extern Gfx mia_Head_Switch_Option_Head_Extra1_DL_mesh_layer_1[];
extern Gfx mia_Head_Switch_Option_Head_Extra1_DL_mesh_layer_1_opt_2[];
extern Gfx mia_Head_Switch_Option_Mouth_DL2_mesh_layer_1[];
extern Gfx mia_Head_Switch_Option_Mouth_DL2_mesh_layer_1_opt_2[];
extern Gfx mia_Head_Switch_Option_Head_Extra2_DL_mesh_layer_1[];
extern Gfx mia_Head_Switch_Option_Head_Extra2_DL_mesh_layer_1_opt_2[];
extern Gfx mia_Head_Switch_Option_Mouth_DL1_mesh_layer_1[];
extern Gfx mia_Head_Switch_Option_Mouth_DL1_mesh_layer_1_opt_2[];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1[];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_opt_1[];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_opt_2[];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_opt_2_0[];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_opt_2_1[];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_opt_2_2[];
extern Gfx mia_Capless_Head_Switch_Option_Mouth_DL_mesh_layer_1[];
extern Gfx mia_Capless_Head_Switch_Option_Mouth_DL_mesh_layer_1_opt_2[];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_Left_Switch_Option_Capless_Head_Left_DL_mesh_layer_1[];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_Left_Switch_Option_Capless_Head_Left_DL_mesh_layer_1_opt_2[];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_Left_Switch_Option_Mouth_DL_mesh_layer_1[];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_Left_Switch_Option_Mouth_DL_mesh_layer_1_opt_2[];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_Right_Switch_Option_Capless_Head_Right_DL_mesh_layer_1[];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_Right_Switch_Option_Capless_Head_Right_DL_mesh_layer_1_opt_2[];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_Right_Switch_Option_Mouth_DL_mesh_layer_1[];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_Right_Switch_Option_Mouth_DL_mesh_layer_1_opt_2[];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_Up_Switch_Option_Capless_Head_Up_DL_mesh_layer_1[];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_Up_Switch_Option_Capless_Head_Up_DL_mesh_layer_1_opt_2[];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_Up_Switch_Option_Mouth_DL_mesh_layer_1[];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_Up_Switch_Option_Mouth_DL_mesh_layer_1_opt_2[];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_Down_Switch_Option_Capless_Head_Down_DL_mesh_layer_1[];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_Down_Switch_Option_Capless_Head_Down_DL_mesh_layer_1_opt_2[];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_Down_Switch_Option_Mouth_DL_mesh_layer_1[];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_Down_Switch_Option_Mouth_DL_mesh_layer_1_opt_2[];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_Dead_Switch_Option_Capless_Head_Dead_DL_mesh_layer_1[];
extern Gfx mia_Capless_Head_Switch_Option_Capless_Head_Dead_Switch_Option_Capless_Head_Dead_DL_mesh_layer_1_opt_2[];
extern Gfx mia_Capless_Head_Switch_Option_Head_Switch_Option_Head_Extra1_Capless_DL_mesh_layer_1[];
extern Gfx mia_Capless_Head_Switch_Option_Head_Switch_Option_Head_Extra1_Capless_DL_mesh_layer_1_opt_2[];
extern Gfx mia_Capless_Head_Switch_Option_Head_Switch_Option_Mouth_DL2_mesh_layer_1[];
extern Gfx mia_Capless_Head_Switch_Option_Head_Switch_Option_Mouth_DL2_mesh_layer_1_opt_2[];
extern Gfx mia_Capless_Head_Switch_Option_Head_Switch_Option_Head_Extra2_Capless_DL_mesh_layer_1[];
extern Gfx mia_Capless_Head_Switch_Option_Head_Switch_Option_Head_Extra2_Capless_DL_mesh_layer_1_opt_2[];
extern Gfx mia_Capless_Head_Switch_Option_Head_Switch_Option_Mouth_DL1_mesh_layer_1[];
extern Gfx mia_Capless_Head_Switch_Option_Head_Switch_Option_Mouth_DL1_mesh_layer_1_opt_2[];
extern Gfx mia_Hair_1_mesh_layer_1[];
extern Gfx mia_Hair_1_mesh_layer_1_opt_2[];
extern Gfx mia_Left_Wing_DL_mesh_layer_4[];
extern Gfx mia_Left_Wing_DL_mesh_layer_4_opt_2[];
extern Gfx mia_MaskSwitchOption_MaskDL_mesh_layer_1[];
extern Gfx mia_MaskSwitchOption_MaskDL_mesh_layer_1_opt_2[];
extern Gfx mia_MaskSwitchOption_MaskDL_mesh_layer_6[];
extern Gfx mia_MaskSwitchOption_MaskDL_mesh_layer_6_opt_2[];
extern Gfx mia_MaskSwitchOption_MaskDL_mesh_layer_6_with_layer_6_revert[];
extern Gfx mia_MaskSwitchOption_MaskDL_mesh_layer_6_opt_2_with_layer_6_revert[];
extern Gfx mia_Right_Wing_DL_mesh_layer_4[];
extern Gfx mia_Right_Wing_DL_mesh_layer_4_opt_2[];
extern Gfx mia_Left_Arm_Color_mesh_layer_1[];
extern Gfx mia_Left_Arm_Color_mesh_layer_1_opt_2[];
extern Gfx mia_Left_Forearm_mesh_layer_1[];
extern Gfx mia_Left_Forearm_mesh_layer_1_opt_2[];
extern Gfx mia_Left_Hand_DL_mesh_layer_1[];
extern Gfx mia_Left_Hand_DL_mesh_layer_1_opt_2[];
extern Gfx mia_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1[];
extern Gfx mia_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1_opt_2[];
extern Gfx mia_Left_Hand_Peace_Switch_Option_Left_Hand_Peace_mesh_layer_1[];
extern Gfx mia_Left_Hand_Peace_Switch_Option_Left_Hand_Peace_mesh_layer_1_opt_2[];
extern Gfx mia_Right_Arm_Color_mesh_layer_1[];
extern Gfx mia_Right_Arm_Color_mesh_layer_1_opt_2[];
extern Gfx mia_Right_Forearm_mesh_layer_1[];
extern Gfx mia_Right_Forearm_mesh_layer_1_opt_2[];
extern Gfx mia_Right_Hand_DL_mesh_layer_1[];
extern Gfx mia_Right_Hand_DL_mesh_layer_1_opt_2[];
extern Gfx mia_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1[];
extern Gfx mia_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1_opt_2[];
extern Gfx mia_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1[];
extern Gfx mia_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1_opt_2[];
extern Gfx mia_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1[];
extern Gfx mia_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1_opt_2[];
extern Gfx mia_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1[];
extern Gfx mia_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1_opt_2[];
extern Gfx mia_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_4[];
extern Gfx mia_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_4_opt_2[];
extern Gfx mia_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_4_with_layer_4_revert[];
extern Gfx mia_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_4_opt_2_with_layer_4_revert[];
extern Gfx mia_Left_Thigh_Color_mesh_layer_1[];
extern Gfx mia_Left_Thigh_Color_mesh_layer_1_opt_2[];
extern Gfx mia_Left_Leg_mesh_layer_1[];
extern Gfx mia_Left_Leg_mesh_layer_1_opt_2[];
extern Gfx mia_Left_Shoe_mesh_layer_1[];
extern Gfx mia_Left_Shoe_mesh_layer_1_opt_2[];
extern Gfx mia_Right_Thigh_Color_mesh_layer_1[];
extern Gfx mia_Right_Thigh_Color_mesh_layer_1_opt_2[];
extern Gfx mia_Right_Leg_mesh_layer_1[];
extern Gfx mia_Right_Leg_mesh_layer_1_opt_2[];
extern Gfx mia_Right_Shoe_DL_mesh_layer_1_with_layer_1_revert[];
extern Gfx mia_Right_Shoe_DL_mesh_layer_1_opt_2_with_layer_1_revert[];
extern Gfx mia_Right_Shoe_DL_mesh_layer_1_with_layer_5_revert[];
